services:
  app:
    build: .
    image: ghcr.io/arinji2/search-backend:latest
    restart: always
    volumes:
      - ./.env:/app/.env
    ports:
      - "57:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/health || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 5s
